// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khmkpqwsnjkhulrbzkyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobWtwcXdzbmpraHVscmJ6a3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTc5OTgsImV4cCI6MjA3MTMzMzk5OH0.q2FqdBrFfIjmDMfxsUsMvcsSAn5qxibKJFoc6A-t_UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});